!
! Chiara Tardioli (tardioli@mail.dm.unipi.it)
! Version: August 29, 2012
! Revised: July 7, 2014 - CT
! --------------------------------------------------------------------- 
!                                                                       
!  *****************************************************************    
!  *                                                               *    
!  *      I N I T I A L   E Q U   O R B I T   C A T A L O G        *
!  *                                                               *    
!  *        Initial conditions for debris orbital elements         *
!  *             at initial epoch teph0 = 55000 MJD               *    
!  *                                                               *
!  *****************************************************************    
!
! =========================================================
! Steps :
! 0) Read the number of VAs by screen
! 1) Read initial orbit given by kepint_lenz
! 2) Do a propagation at epoch teph0
! 2) Write the new orbit into 'allorbits.fla'
! =========================================================
PROGRAM lenz_cat
  USE fund_const
  USE orbit_elements
  USE option_file
  IMPLICIT NONE
! --------------------------------------------------
! options
  CHARACTER*6 :: progna
  CHARACTER*80 :: run
! --------------------------------------------------
! for reading orbit elements
!  INTEGER,PARAMETER :: norbx=1200
!  CHARACTER*80 :: catnam
  INTEGER :: norb !number of orbits in the catalog
  CHARACTER*9,DIMENSION(norbx) :: name
  TYPE(orbit_elem),DIMENSION(norbx) :: elem
! -------------------------------------------------
! for elem_propag
  REAL(KIND=dkind) :: t1
  TYPE(orbit_elem) :: el1
  REAL(kind=dkind),DIMENSION(5,5) :: unc1,unc
! for enlarge the orbit catalog
  TYPE(orbit_elem),DIMENSION(norbx) :: el1_wide
  INTEGER :: m     !the number of virtual orbits is 2m+1 for each asteroid
! loop indeces
  INTEGER :: iun,i,j,k
! --------------------------------------------------
  rhs=2
  t1=55000
  write(*,*)'initial evolution epoch',t1
! options
  progna='orbsrv' 
  run='dmint_opt'
  CALL compop

! Reading orbital data from allslenzall_nor.out...
  CALL read_lenz(norb,name,elem)
  write(*,*)'No. of orbit: ',norb

! write output at the same epoch t1
  CALL filopn(iun,'allorbits.fla','UNKNOWN')
  j=0
! ****** uncertainty are set zero *****
  unc1=0.d0
  unc=0.d0
! *************************************
  WRITE(*,*)'Insert an integer m>0, 2m+1 is the number of Virtual Orbits for each asteroid to create (0 for no VO):'
  READ(*,*)m
  DO i=1,norb
     IF(elem(i)%coord(1).gt.8600.d3)THEN
        GOTO 5
     ENDIF
! orbit evolution at epoch t1=5500 MJD
!     write(*,*)elem(i)%t,elem(i)%coord(1:6)
     el1%t=t1
     CALL elem_propag(t1-elem(i)%t,elem(i),unc,el1,unc1)

     IF(m.gt.0)THEN
! Create 2m+1 virtual orbits
        CALL enlarge_orbit(m,el1,el1_wide)
        DO k=1,2*m+1
           CALL write_lenz(iun,el1_wide(k))
           j=j+1
        ENDDO
     ELSE
        CALL write_lenz(iun,el1)
        j=j+1
     ENDIF

!     write(*,*)el1%t,el1%coord(1:6)
5    CONTINUE
  ENDDO
  CALL filclo(iun,' ')
  write(*,*)'no. of orbts with s.m.axis < 8600 km',j
! ------------------ end main program ---------------



CONTAINS

SUBROUTINE compop 
  IMPLICIT NONE
  INTEGER            :: le,iunout
  CHARACTER(LEN=100) :: file 
  LOGICAL            :: ireq,found
  CHARACTER(LEN=60)  :: comment 
! =============================  
  CALL initopt(progna,run,'mop')  
! read option for physical model and integration method                 
  CALL rmodel(rhs)    
  END SUBROUTINE compop

END PROGRAM lenz_cat

! *********************************************
! WRITING ORBIT DATA GENERATED BY KEPINT_LENZ
! in a flat file
! *********************************************
SUBROUTINE write_lenz(iun,ele)
  USE fund_const
  USE orbit_elements
  USE orbit_elements
  IMPLICIT NONE
! ----------------- interface -----------------------------------
  INTEGER,INTENT(IN) :: iun
  TYPE(orbit_elem),INTENT(IN) :: ele
! ---------------- end interface --------------------------------

  write(iun,107)ele%coord(1:6)
107 FORMAT(f12.3,2x,e16.10,4(2x,f16.14))

END SUBROUTINE write_lenz

! *********************************************
! ENLARGE ORBIT CATALOG GENERATED BY KEPINT_LENZ
! no orbit uncertainty
! *********************************************
SUBROUTINE enlarge_orbit(m,elem_lenz,elem)
  USE fund_const
  USE orbit_elements
  USE option_file
  IMPLICIT NONE
  REAL(KIND=dkind),PARAMETER :: eps_inc=8.d-2 !step size in inclination
! ----------------- interface -----------------------------------
  INTEGER :: m !2m+1 is the number of alias
  TYPE(orbit_elem),INTENT(IN) :: elem_lenz
  TYPE(orbit_elem),DIMENSION(5),INTENT(OUT) :: elem
! ---------------- end interface --------------------------------
  REAL(KIND=dkind) :: princ
  INTEGER :: i,j  !loop indeces
! ---------------------------------------------------------------
! The nominal solution corrisponds to j=m+1
  elem(m+1) = undefined_orbit_elem
  elem(m+1) = elem_lenz
  DO j=1,m
     elem(j) = undefined_orbit_elem
     elem(j) = elem_lenz
     elem(j)%coord(3) = princ(elem_lenz%coord(3) - j*eps_inc)

     elem(m+1+j) = undefined_orbit_elem
     elem(m+1+j) = elem_lenz
     elem(m+1+j)%coord(3) = princ(elem_lenz%coord(3) + j*eps_inc)
  ENDDO
END SUBROUTINE enlarge_orbit
